Repository inplayer-org/inplayer-ui, pull requests merged in 2019-05, with the labels that each got.

#206 [0.15.0] - 09-05-2019
  .flowconfig
  CHANGELOG.md
  docs/build/1.11370eef.js
  docs/build/1.1a279797.js
  docs/build/bundle.75acf81b.js
  docs/build/bundle.fce619ff.js
  docs/index.d.ts
  docs/index.html
  flow-typed/npm/styled-components-modifiers_vx.x.x.jsstyled-components-modifiers_vx.x.x.jsstyled-components-modifiers_vx.x.x.js
  flow-typed/npm/styled-components_v3.x.x.js
  flow-typed/npm/styled-components_v4.x.x.js
  package.json
  src/elements/DatePicker/index.js
  src/elements/DatePicker/tests/__snapshots__/index.js.snap
  src/elements/DatePickerWrapper.js
  src/elements/DayPicker/DayPickerWrapper.js
  src/elements/DayPicker/Readme.md
  src/elements/DayPicker/index.js
  src/elements/SingleDayPicker/Readme.md
  src/elements/SingleDayPicker/index.js
  src/elements/SingleDayPicker/test/index.js
  src/elements/index.js
  src/index.d.ts
  yarn.lock
Labels: new version

#209 [0.15.1] - 15-05-2019
  CHANGELOG.md
  package.json
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/AccordionPanel.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Accordion/styled.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: new version

#211 210/Change: Make DatePicker elements endDate prop optional
  CHANGELOG.md
  package.json
  src/elements/DatePicker/index.js
  src/index.d.ts
Labels: improvement

#214 Create Step Wizard
  CHANGELOG.md
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/StepWizard/Nav.js
  src/elements/StepWizard/Readme.md
  src/elements/StepWizard/Step.js
  src/elements/StepWizard/index.js
  src/elements/StepWizard/tests/__snapshots__/index.js.snap
  src/elements/StepWizard/tests/index.js
  src/elements/index.js
  src/index.d.ts
Labels: feature

#213 Modify tooltip behavior
  CHANGELOG.md
  src/components/Tooltip/Arrow.js
  src/components/Tooltip/Bubble.js
  src/components/Tooltip/Readme.md
  src/components/Tooltip/Tooltip.js
  src/components/Tooltip/TooltipWrapper.js
  src/components/Tooltip/index.js
  src/components/Tooltip/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: improvement

#217 [0.16.1] - 22-05-2019
  CHANGELOG.md
  docs/build/bundle.43763fa9.js
  docs/index.html
  package.json
  src/components/Tooltip/tests/__snapshots__/index.js.snap
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/AccordionPanel.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
Labels: new version

#219 Add Step completion
  CHANGELOG.md
  package.json
  src/elements/StepWizard/Nav.js
  src/elements/StepWizard/Readme.md
  src/elements/StepWizard/index.js
  src/index.d.ts
Labels: feature
