Repository inplayer-org/inplayer-ui, pull requests merged in 2019-11, with the labels that each got.

#494 v2.0.0-beta.1
  CHANGELOG.md
  docs/build/bundle.a2b73815.js
  docs/build/bundle.c22d184c.js
  docs/build/bundle.c22d184c.js.LICENSE
  docs/index.html
  package.json
  src/elements/Accordion/AccordionPanel.js
  yarn.lock
Labels: new version

#514 Problem with margin in merchant panel
  CHANGELOG.md
  src/elements/Typography/index.js
Labels: hotfix

#524 Custom date presets
  CHANGELOG.md
  src/elements/DatePicker/Readme.md
  src/elements/DatePicker/index.js
  src/index.d.ts
Labels: improvement
