Repository inplayer-org/inplayer-ui, pull requests merged in 2019-08, with the labels that each got.

#373 Update webfontloader active in globalStyles
  CHANGELOG.md
  src/config/globalStyles.js
  src/elements/Progress/tests/__snapshots__/index.js.snap
Labels: bug

#374 [0.25.1] - 01-08-2019
  .gitignore
  CHANGELOG.md
  docs/build/bundle.8434766c.js
  docs/index.d.ts
  docs/index.html
  package.json
  src/config/globalStyles.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Progress/tests/__snapshots__/index.js.snap
  src/index.d.ts
  yarn.lock
Labels: new version

#397 [0.25.2] - 15-08-2019
  CHANGELOG.md
  docs/build/bundle.921986ad.js
  docs/index.d.ts
  docs/index.html
  package.json
  src/components/Table/index.js
  src/components/Table/tests/__snapshots__/index.js.snap
  src/index.d.ts
  yarn.lock
Labels: new version

#411 Fix Radio styling
  .eslintrc
  CHANGELOG.md
  src/components/Radio/RadioWrapper.js
  src/components/Radio/Readme.md
  src/components/Radio/tests/__snapshots__/index.js.snap
  src/elements/DatePicker/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
Labels: improvement
