Repository inplayer-org/inplayer-ui, pull requests merged in 2019-07, with the labels that each got.

#311 Style dropdown consistently accross browsers
  CHANGELOG.md
  src/elements/Dropdown/index.js
  src/elements/Dropdown/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
Labels: improvement

#312 [0.19.2] - 02-07-2019
  CHANGELOG.md
  docs/build/bundle.bf856e28.js
  docs/index.html
  package.json
  src/elements/Dropdown/index.js
  src/elements/Dropdown/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
Labels: new version

#313 Use svg background image for Dropdown arrow
  CHANGELOG.md
  src/elements/Dropdown/index.js
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
Labels: improvement

#315 [0.19.3] - 03-07-2019
  CHANGELOG.md
  docs/build/bundle.92d16875.js
  docs/index.html
  package.json
  src/elements/Accordion/AccordionFooter.js
  src/elements/Dropdown/index.js
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
  yarn.lock
Labels: new version

#318 [0.19.4] - 04-07-2019
  CHANGELOG.md
  docs/build/bundle.d68ca642.js
  docs/index.html
  package.json
  src/elements/Dropdown/index.js
  src/elements/Dropdown/tests/__snapshots__/index.test.js.snap
  src/elements/Dropdown/tests/index.test.js
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
Labels: new version

#332 Add missing optional prop disable - radio component
  CHANGELOG.md
  src/components/Radio/index.js
  src/components/Radio/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: improvement

#333 Close accordion render prop
  CHANGELOG.md
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Accordion/tests/index.js
  src/index.d.ts
Labels: improvement

#335 Merge dev branch into master
  CHANGELOG.md
  docs/build/bundle.6b2b8103.js
  docs/index.d.ts
  docs/index.html
  package.json
  src/components/Radio/index.js
  src/components/Radio/tests/__snapshots__/index.js.snap
  src/components/Tooltip/Bubble.js
  src/components/Tooltip/Readme.md
  src/components/Tooltip/index.js
  src/components/Tooltip/tests/__snapshots__/index.js.snap
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Accordion/tests/index.js
  src/index.d.ts
  yarn.lock
Labels: new version

#351 Missing optional prop disabled in Checkbox component
  CHANGELOG.md
  src/components/Checkbox/index.js
  src/components/Checkbox/tests/__snapshots__/index.js.snap
  src/components/Table/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: improvement

#352 New version
  CHANGELOG.md
  docs/build/bundle.7da61da8.js
  docs/index.d.ts
  docs/index.html
  package.json
  src/components/Checkbox/index.js
  src/components/Checkbox/tests/__snapshots__/index.js.snap
  src/components/Table/tests/__snapshots__/index.js.snap
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Accordion/tests/index.js
  src/elements/Progress/tests/__snapshots__/index.js.snap
  src/index.d.ts
  yarn.lock
Labels: new version

#363 Add disabled and iconTooltip options to Accordion
  CHANGELOG.md
  src/components/Tooltip/index.js
  src/elements/Accordion/AccordionPanel.js
  src/elements/Accordion/Readme.md
  src/elements/Accordion/index.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Progress/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: bug, feature, improvement
