Repository inplayer-org/inplayer-ui, pull requests merged in 2019-12, with the labels that each got.

#537 Create Avatar component
  CHANGELOG.md
  src/elements/Avatar/Readme.md
  src/elements/Avatar/index.js
  src/elements/Avatar/tests/index.js
Labels: feature

#543 336/chore/inplayer icon docs
  docs/build/bundle.2b7a6728.js
  docs/build/bundle.2b7a6728.js.LICENSE
  src/elements/InPlayerIcon/Readme.md
  src/elements/InPlayerIcon/index.js
Labels: improvement

#551 Feature: Add Header Section to Table
  .babelrc
  CHANGELOG.md
  package.json
  src/components/Table/Readme.md
  src/components/Table/index.js
  src/elements/Accordion/AccordionPanel.js
  src/index.d.ts
  yarn.lock
Labels: feature

#556 fix Table's border-inclusion logic when headerSection option is omitted
  CHANGELOG.md
  src/components/Table/index.js
  src/index.d.ts
Labels: bug

#558 add Table renderEmptyTable boolean prop
  CHANGELOG.md
  package.json
  src/components/Table/index.js
  src/index.d.ts
Labels: improvement
