Repository inplayer-org/inplayer-ui, pull requests merged in 2019-03, with the labels that each got.

#138 No issue/fix/fix pagination issues
  CHANGELOG.md
  src/components/Table/tests/__snapshots__/index.js.snap
  src/components/Tooltip/tests/__snapshots__/index.js.snap
  src/elements/Pagination/index.js
  src/elements/Pagination/tests/__snapshots__/index.js.snap
Labels: hotfix

#140 139/hotfix/update pagination props
  CHANGELOG.md
  src/elements/Pagination/index.js
Labels: bug

#153 Add fullheight prop to Button
  CHANGELOG.md
  src/elements/Button/ButtonWrapper.js
  src/index.d.ts
Labels: improvement

#161 Add margin left to the Label in Switch component
  CHANGELOG.md
  src/elements/Switch/index.js
  src/elements/Switch/tests/__snapshots__/index.js.snap
Labels: hotfix, improvement

#166 Forward ref to Input component
  CHANGELOG.md
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: hotfix

#164 Fix: optional date props & changed dates type
  CHANGELOG.md
  src/elements/DatePicker/index.js
  src/index.d.ts
Labels: hotfix

#167 v0.10.3 & v0.10.4
  CHANGELOG.md
  docs/build/bundle.5425b5d7.js
  docs/index.d.ts
  docs/index.html
  package.json
  src/elements/DatePicker/index.js
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: new version

#168 No issue/feature/add inplayer icon component
  .eslintignore
  CHANGELOG.md
  jsconfig.json
  package.json
  src/assets/fonts/ipic18.eot
  src/assets/fonts/ipic18.svg
  src/assets/fonts/ipic18.ttf
  src/assets/fonts/ipic18.woff
  src/config/globalStyles.js
  src/elements/InPlayerIcon/Readme.md
  src/elements/InPlayerIcon/index.js
  src/elements/index.js
  src/index.d.ts
  webpack.config.js
  yarn.lock
Labels: feature

#172 Remove fixed width in Input component
  CHANGELOG.md
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
Labels: hotfix, improvement

#175 Use same padding value for Input and Dropdown
  CHANGELOG.md
  src/components/Modal/ModalContent.js
  src/components/Modal/ModalHeader.js
  src/components/Modal/tests/__snapshots__/index.js.snap
  src/components/NavBar/Arrow.js
  src/components/NavBar/MenuItem.js
  src/components/NavBar/styled.js
  src/components/NavBar/tests/__snapshots__/Arrow.test.js.snap
  src/components/NavBar/tests/__snapshots__/MenuItem.test.js.snap
  src/components/NavBar/tests/__snapshots__/MenuWithLogo.test.js.snap
  src/components/NavBar/tests/__snapshots__/index.js.snap
  src/components/Note/NoteWrapper.js
  src/components/Note/tests/__snapshots__/index.js.snap
  src/components/Radio/RadioWrapper.js
  src/components/Radio/tests/__snapshots__/index.js.snap
  src/components/TabNavigation/index.js
  src/components/TabNavigation/tests/__snapshots__/index.js.snap
  src/components/Table/index.js
  src/components/Table/tests/__snapshots__/index.js.snap
  src/components/UserMenu/UserMenuDropdown.js
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/AccordionPanel.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Button/ButtonWrapper.js
  src/elements/Button/tests/__snapshots__/index.js.snap
  src/elements/Card/index.js
  src/elements/Card/tests/__snapshots__/index.js.snap
  src/elements/DatePicker/DateRangePickerWrapper.js
  src/elements/DatePicker/tests/__snapshots__/index.js.snap
  src/elements/DatePickerWrapper.js
  src/elements/Dropdown/index.js
  src/elements/Dropdown/tests/__snapshots__/index.js.snap
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Notification/NotificationContainer.js
  src/elements/Notification/tests/__snapshots__/index.js.snap
  src/elements/Pagination/PaginationWrapper.js
  src/elements/Pagination/tests/__snapshots__/index.js.snap
  src/elements/PillLabel/index.js
  src/elements/PillLabel/tests/__snapshots__/index.js.snap
  src/elements/SingleDayPicker/SingleDayPickerWrapper.js
  src/elements/Switch/SwitchWrapper.js
  src/elements/Switch/tests/__snapshots__/index.js.snap
  src/elements/TextArea/index.js
  src/elements/TextArea/tests/__snapshots__/index.js.snap
Labels: improvement

#176 v0.11.1
  CHANGELOG.md
  docs/build/bundle.bd4fd863.js
  docs/index.html
  package.json
  src/components/Modal/ModalContent.js
  src/components/Modal/ModalHeader.js
  src/components/Modal/tests/__snapshots__/index.js.snap
  src/components/NavBar/Arrow.js
  src/components/NavBar/MenuItem.js
  src/components/NavBar/styled.js
  src/components/NavBar/tests/__snapshots__/Arrow.test.js.snap
  src/components/NavBar/tests/__snapshots__/MenuItem.test.js.snap
  src/components/NavBar/tests/__snapshots__/MenuWithLogo.test.js.snap
  src/components/NavBar/tests/__snapshots__/index.js.snap
  src/components/Note/NoteWrapper.js
  src/components/Note/tests/__snapshots__/index.js.snap
  src/components/Radio/RadioWrapper.js
  src/components/Radio/tests/__snapshots__/index.js.snap
  src/components/TabNavigation/index.js
  src/components/TabNavigation/tests/__snapshots__/index.js.snap
  src/components/Table/index.js
  src/components/Table/tests/__snapshots__/index.js.snap
  src/components/UserMenu/UserMenuDropdown.js
  src/elements/Accordion/AccordionFooter.js
  src/elements/Accordion/AccordionPanel.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Button/ButtonWrapper.js
  src/elements/Button/tests/__snapshots__/index.js.snap
  src/elements/Card/index.js
  src/elements/Card/tests/__snapshots__/index.js.snap
  src/elements/DatePicker/DateRangePickerWrapper.js
  src/elements/DatePicker/tests/__snapshots__/index.js.snap
  src/elements/DatePickerWrapper.js
  src/elements/Dropdown/index.js
  src/elements/Dropdown/tests/__snapshots__/index.js.snap
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Notification/NotificationContainer.js
  src/elements/Notification/tests/__snapshots__/index.js.snap
  src/elements/Pagination/PaginationWrapper.js
  src/elements/Pagination/tests/__snapshots__/index.js.snap
  src/elements/PillLabel/index.js
  src/elements/PillLabel/tests/__snapshots__/index.js.snap
  src/elements/SingleDayPicker/SingleDayPickerWrapper.js
  src/elements/Switch/SwitchWrapper.js
  src/elements/Switch/tests/__snapshots__/index.js.snap
  src/elements/TextArea/index.js
  src/elements/TextArea/tests/__snapshots__/index.js.snap
Labels: new version

#178 Center button content in middle
  CHANGELOG.md
  src/elements/Button/ButtonWrapper.js
  src/elements/Button/Readme.md
  src/elements/Button/index.js
  src/elements/Button/tests/__snapshots__/index.js.snap
Labels: improvement

#180 Create Input sizes
  CHANGELOG.md
  src/components/Table/Readme.md
  src/components/Table/index.js
  src/components/Table/tests/__snapshots__/index.js.snap
  src/elements/Accordion/styled.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Input/Readme.md
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Switch/index.js
  src/elements/TextArea/index.js
  src/elements/TextArea/tests/__snapshots__/index.js.snap
  src/elements/Typography/index.js
  src/index.d.ts
Labels: improvement

#182 v0.12.0
  CHANGELOG.md
  docs/build/bundle.4f3ff0d6.js
  docs/index.d.ts
  docs/index.html
  package.json
  src/components/Table/Readme.md
  src/components/Table/index.js
  src/components/Table/tests/__snapshots__/index.js.snap
  src/elements/Accordion/styled.js
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Button/ButtonWrapper.js
  src/elements/Button/Readme.md
  src/elements/Button/index.js
  src/elements/Button/tests/__snapshots__/index.js.snap
  src/elements/Input/Readme.md
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Switch/index.js
  src/elements/TextArea/index.js
  src/elements/TextArea/tests/__snapshots__/index.js.snap
  src/elements/Typography/index.js
  src/index.d.ts
Labels: new version

#184 Enable Button to accept custom Icon as prop
  CHANGELOG.md
  src/elements/Button/Readme.md
  src/elements/Button/index.js
  src/index.d.ts
Labels: feature
