Repository inplayer-org/inplayer-ui, pull requests merged in 2019-10, with the labels that each got.

#460 Initial Major Version
  .babelrc
  .eslintrc
  CHANGELOG.md
  package.json
  src/components/NavBar/index.js
  src/components/Tabs/index.js
  src/components/UserMenu/index.js
  src/elements/DayPicker/DayPickerWrapper.js
  src/elements/DayPicker/Readme.md
  src/elements/DayPicker/index.js
  src/elements/Input/index.js
  src/index.d.ts
  src/theme/ThemeWrapper.js
  webpack.config.js
  yarn.lock
Labels: new version

#468 Update npm libs
  package.json
  yarn.lock
Labels: improvement

#473 Fix: Invalid date in day picker
  .eslintrc
  CHANGELOG.md
  src/elements/DayPicker/index.js
Labels: bug

#474 v1.0.4
  .eslintrc
  CHANGELOG.md
  docs/build/bundle.14873c83.js
  docs/build/bundle.14873c83.js.LICENSE
  docs/build/bundle.c9d616dd.js
  docs/index.html
  package.json
  src/elements/DayPicker/index.js
  yarn.lock
Labels: new version

#482 v1.1.0
  CHANGELOG.md
  docs/build/bundle.14873c83.js
  docs/build/bundle.7011bfc4.js
  docs/build/bundle.7011bfc4.js.LICENSE
  docs/index.d.ts
  docs/index.html
  package.json
  src/elements/Input/Readme.md
  src/elements/Input/index.js
  src/index.d.ts
  yarn.lock
Labels: new version

#488 Update npm libs to latest version
  package.json
  yarn.lock
Labels: improvement
