Repository inplayer-org/inplayer-ui, pull requests merged in 2019-02, with the labels that each got.

#101 Make Label disabled prop optional
  CHANGELOG.md
  src/config/globalStyles.js
  src/index.d.ts
Labels: bug, improvement

#102 No issue/fix/Fix MenuItem width
  src/components/NavBar/MenuItem.js
  src/index.d.ts
Labels: bug, improvement

#108 Fix: TextField of type search styling bug
  CHANGELOG.md
  src/components/Header/tests/__snapshots__/index.js.snap
  src/components/TabNavigation/tests/__snapshots__/index.js.snap
  src/elements/TextField/index.js
  src/index.d.ts
  src/theme/ThemeWrapper.js
Labels: bug

#116 Fix typescript definition props
  CHANGELOG.md
  src/index.d.ts
Labels: hotfix

#119 Add missing modifier definitions, remove/edit margins for Typography/Label
  CHANGELOG.md
  src/components/Checkbox/tests/__snapshots__/index.js.snap
  src/components/Modal/tests/__snapshots__/index.js.snap
  src/components/Radio/tests/__snapshots__/index.js.snap
  src/components/Table/tests/__snapshots__/index.js.snap
  src/elements/Accordion/tests/__snapshots__/index.js.snap
  src/elements/Label/index.js
  src/elements/Label/tests/__snapshots__/index.js.snap
  src/elements/Switch/tests/__snapshots__/index.js.snap
  src/elements/Typography/index.js
  src/elements/Typography/tests/__snapshots__/index.js.snap
  src/index.d.ts
Labels: hotfix, improvement

#125 HOTFIX: Update Button TypeScript Definitions
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  src/index.d.ts
Labels: hotfix

#127 126/improvement/rename textfield to input
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  src/blocks/Grid/Cell.js
  src/components/Table/Readme.md
  src/elements/Card/CardContent.js
  src/elements/Card/index.js
  src/elements/Card/tests/__snapshots__/index.js.snap
  src/elements/Input/Readme.md
  src/elements/Input/index.js
  src/elements/Input/tests/__snapshots__/index.js.snap
  src/elements/Input/tests/index.js
  src/elements/TextField/tests/index.js
  src/elements/index.js
  src/index.d.ts
Labels: improvement
