Repository inplayer-org/inplayer-ui, pull requests merged in 2020-07, with the labels that each got.

#1012 Make max number of items to be 10000 in pagination
  CHANGELOG.md
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/pagination.stories.mdx
Labels: bug

#1016 fix: use Math.floor only if totalItemsNumber is 10.000 in Pagination …
  CHANGELOG.md
  src/components/Pagination/Pagination.tsx
Labels: bug, hotfix

#1024 Merge master with dev
  CHANGELOG.md
  index.d.ts
  package.json
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/pagination.stories.mdx
  src/components/Switch/Switch.tsx
  yarn.lock
Labels: feature, improvement

#1028 Display next 100 years in date picker select
  CHANGELOG.md
  src/utils/helpers.ts
Labels: improvement
