Repository inplayer-org/inplayer-ui, pull requests merged in 2020-02, with the labels that each got.

#580 Make table responsive
  CHANGELOG.md
  src/components/Table/index.js
Labels: hotfix, improvement

#575 Created custom pagination component
  CHANGELOG.md
  package.json
  src/components/Pagination/Readme.md
  src/components/Pagination/index.js
  src/components/index.js
  src/elements/Pagination/PaginationWrapper.js
  src/elements/Pagination/Readme.md
  src/elements/Pagination/index.js
  src/elements/index.js
  src/index.d.ts
  yarn.lock
Labels: improvement

#608 Feature: Paywall Preview Templates
  .babelrc
  .stylelintrc
  README.md
  jsconfig.json
  package.json
  public/index.html
  src/app.js
  src/assets/images/ip-icon-blue.svg
  src/assets/images/ip-preview-premium.png
  src/assets/images/restricted-asset.png
  src/index.d.ts
  src/index.js
  src/previews/Preview1/index.js
  src/previews/Preview1/styled.js
  src/previews/Preview2/index.js
  src/previews/Preview2/styled.js
  src/previews/Preview3/index.js
  src/previews/Preview3/styled.js
  src/previews/Preview4/index.js
  src/previews/Preview4/styled.js
  src/previews/Preview5/index.js
  src/previews/Preview5/styled.js
  src/previews/Preview6/index.js
  src/previews/Preview6/styled.js
  src/previews/Preview7/index.js
  src/previews/Preview7/styled.js
  src/previews/components/SharedComponents.js
  src/previews/components/StyledContainer.js
  src/previews/components/TextEditor.js
  src/previews/index.js
  src/previews/types/branding.js
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: feature
