Repository inplayer-org/inplayer-ui, pull requests merged in 2020-05, with the labels that each got.

#823 Fix preview 1
  src/paywall-previews/Preview1/Preview1.tsx
  src/paywall-previews/Preview1/styled.ts
Labels: improvement

#824 Fix: Paywall Preview 2 layout
  src/paywall-previews/Preview2/styled.ts
Labels: improvement

#826 Fix: Paywall Preview 6 layout
  src/paywall-previews/Preview6/styled.ts
Labels: improvement

#827 Fix/storybook docs
  package.json
  public/index.html
  src/app.tsx
  src/components/Card/card.stories.mdx
  src/components/Checkbox/checkbox.stories.mdx
  src/components/DatePicker/datepicker.stories.mdx
  src/components/DayPicker/daypicker.stories.mdx
  src/components/Dropdown/dropdown.stories.mdx
  src/components/Header/header.stories.mdx
  src/components/Table/Table.tsx
  src/paywall-previews/Preview1/Preview1.tsx
  src/paywall-previews/Preview1/preview1.stories.mdx
  src/paywall-previews/Preview1/styled.ts
  src/paywall-previews/Preview2/Preview2.tsx
  src/paywall-previews/Preview2/preview2.stories.mdx
  src/paywall-previews/Preview2/styled.ts
  src/paywall-previews/Preview3/Preview3.tsx
  src/paywall-previews/Preview3/preview3.stories.mdx
  src/paywall-previews/Preview3/styled.tsx
  src/paywall-previews/Preview4/Preview4.tsx
  src/paywall-previews/Preview4/preview4.stories.mdx
  src/paywall-previews/Preview5/Preview5.tsx
  src/paywall-previews/Preview5/preview5.stories.mdx
  src/paywall-previews/Preview5/styled.ts
  src/paywall-previews/Preview6/Preview6.tsx
  src/paywall-previews/Preview6/preview6.stories.mdx
  src/paywall-previews/Preview6/styled.ts
  src/paywall-previews/Preview7/Preview7.tsx
  src/paywall-previews/Preview7/preview7.stories.mdx
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: hotfix, improvement

#850 Fix/inplayer ui
  src/components/Modal/Modal.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/RadioWrapper.tsx
Labels: improvement

#861 Hotfix: Component fixes
  src/components/Button/Button.tsx
  src/components/Button/ButtonWrapper.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalContent.tsx
  src/index.d.ts
Labels: hotfix

#910 Remove button outline
  src/components/Button/ButtonWrapper.ts
Labels: improvement

#903 Center button content
  dist/index.d.ts
  dist/inplayer-ui.min.js
  dist/inplayer-ui.min.js.LICENSE.txt
  src/components/Button/Button.tsx
  src/components/Input/Input.tsx
Labels: improvement
